# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15abnX_HeeEpTcAxX5ghI58FrsZP_MxQ-
"""

import pandas as pd

# Load Excel file
file_path = "/content/SalesDashboard.xlsx"
xls = pd.ExcelFile(file_path)

# Load specific sheets
calculations = pd.read_excel(xls, sheet_name="calculations")
dashboards = pd.read_excel(xls, sheet_name="Dashboard")

# Extract Sales Data
sales_data = calculations.iloc[2:5, [5, 6, 7, 8]]  # Extract relevant columns
sales_data.columns = ["Metric", "Latest Month", "Previous Month", "Growth Rate"]
sales_data = sales_data.dropna()

# Ensure the script can handle new data dynamically
sales_data = sales_data.sort_values(by="Latest Month", ascending=False)

# Display results
print("Sales Performance Overview")
print(sales_data)

# Save cleaned data for visualization
sales_data.to_csv("/sales_summary.csv", index=False)